Repository memorysafety/river, pull requests merged in 2024-04, with the labels that each got.

#21 Provide a root workspace
  Cargo.toml
Labels: F-Tooling

#19 Add "Basic Proxy" configuration
  README.md
  source/river/Cargo.toml
  source/river/assets/example-config.toml
  source/river/assets/test-config.toml
  source/river/assets/test.crt
  source/river/assets/test.key
  source/river/src/config/cli.rs
  source/river/src/config/internal.rs
  source/river/src/config/mod.rs
  source/river/src/config/toml.rs
  source/river/src/main.rs
  source/river/src/proxy.rs
Labels: F-Downstream, F-Upstream, F-Configuration

#22 Update Workspace to use Resolver 2
  Cargo.toml
Labels: F-Tooling

#27 Initial filter implementation
  source/river/Cargo.toml
  source/river/assets/test-config.toml
  source/river/src/config/internal.rs
  source/river/src/config/toml.rs
  source/river/src/main.rs
  source/river/src/proxy.rs
  source/river/src/proxy/mod.rs
  source/river/src/proxy/request_modifiers.rs
  source/river/src/proxy/response_modifiers.rs
Labels: F-RequestPathCtl
